postgres: guidance on using read-only for old dbs
XGOV SLACK:

"""
kevkeenoy_mhclg Sep 24th at 2:10 PM
Hello... seems like read-only conduits aren't working quite as expected - I opened one to one of our DBs but get...
rdsbroker_d2c440cc_eb3b_4a76_98f3_71b9906644b6=> select * from clients;
ERROR:  permission denied for table clients

tlwr_gds  4 days ago
Hi, yes I’ve seen this happen in other databases
Whenever a view/table/schema gets created (by a non-read-only user) we propagate permissions to the read-only group.
This means if you use a read-only user but permissions haven’t yet been propagated, then it does not have access to the table.
You can either (as a non-read-only user) run
SELECT make_readable_generic()
which is a function we use to allocate permissions
or just
CREATE SCHEMA foo;
DROP SCHEMA foo;
"""

Signed-off-by: Toby Lorne <toby.lornewelch-richards@digital.cabinet-office.gov.uk>